-- This script initializes the database by creating tables and inserting data
-- Use only for a proof of concept
DROP TABLE USERS IF EXISTS CASCADE;
DROP SEQUENCE HIBERNATE_SEQUENCE IF EXISTS;

CREATE TABLE INTERNS (
  NAME VARCHAR(255),
  EMAIL VARCHAR(255) PRIMARY KEY);
  
CREATE TABLE PROJECTS (
	NAME VARCHAR(255) PRIMARY KEY,
	MAXPEOPLE VARCHAR(500));


INSERT INTO INTERNS (NAME, EMAIL) VALUES ('Jon Doe', 'jdoe@redhat.com');

INSERT INTO PROJECTS (NAME, MAXPEOPLE) VALUES ('Snowdrop', '3');
